version: '2'
services:
  app:
    build: .
    restart: always
    environment:
      - MONGO_URL=mongodb://palindrome_db:27017
      - APP_PORT=8080
    ports:
      - "8080:8080"
    links:
      - db:palindrome_db
    depends_on:
      - db
  db:
    restart: always
    image: mongo